apiVersion: apps/v1
kind: Deployment
metadata:
  name: influxdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: influxdb
  template:
    metadata:
      labels:
        app: influxdb
    spec:
      containers:
      - name: influxdb
        image: influxdb:alpine
        ports:
          - containerPort: 8086
        env:
        - name: INFLUXDB_DB
          value: worker
        - name: INFLUXDB_READ_USER
          value: worker
        - name: INFLUXDB_READ_USER_PASSWORD
          value: "ADD PASSWORD HERE"
        - name: INFLUXDB_WRITE_USER
          value: worker
        - name: INFLUXDB_WRITE_USER_PASSWORD
          value: "ADD PASSWORD HERE"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chronograf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chronograf
  template:
    metadata:
      labels:
        app: chronograf
    spec:
      containers:
      - name: chronograf
        image: chronograf
        command: ["chronograf", "--influxdb-url=http://influxdb:8086", "--influxdb-username=worker", "--influxdb-password=YOUR_PASSWORD"]
---
apiVersion: v1
kind: Service
metadata:
  name: chronograf
spec:
  type: NodePort
  selector:
    app: chronograf
  ports:
    - port: 8888
      targetPort: 8888
      nodePort: 30001